import type { KeyGlyphMap, Layout } from "~/types";

const g = (main: string, shift: string) => ({ main, shift });

const EN: KeyGlyphMap = {
  Backquote: g("`", "~"),
  Digit1: g("1", "!"),
  Digit2: g("2", "@"),
  Digit3: g("3", "#"),
  Digit4: g("4", "$"),
  Digit5: g("5", "%"),
  Digit6: g("6", "^"),
  Digit7: g("7", "&"),
  Digit8: g("8", "*"),
  Digit9: g("9", "("),
  Digit0: g("0", ")"),
  Minus: g("-", "_"),
  Equal: g("=", "+"),
  KeyQ: g("q", "Q"),
  KeyW: g("w", "W"),
  KeyE: g("e", "E"),
  KeyR: g("r", "R"),
  KeyT: g("t", "T"),
  KeyY: g("y", "Y"),
  KeyU: g("u", "U"),
  KeyI: g("i", "I"),
  KeyO: g("o", "O"),
  KeyP: g("p", "P"),
  BracketLeft: g("[", "{"),
  BracketRight: g("]", "}"),
  Backslash: g("\\", "|"),
  KeyA: g("a", "A"),
  KeyS: g("s", "S"),
  KeyD: g("d", "D"),
  KeyF: g("f", "F"),
  KeyG: g("g", "G"),
  KeyH: g("h", "H"),
  KeyJ: g("j", "J"),
  KeyK: g("k", "K"),
  KeyL: g("l", "L"),
  Semicolon: g(";", ":"),
  Quote: g("'", '"'),
  KeyZ: g("z", "Z"),
  KeyX: g("x", "X"),
  KeyC: g("c", "C"),
  KeyV: g("v", "V"),
  KeyB: g("b", "B"),
  KeyN: g("n", "N"),
  KeyM: g("m", "M"),
  Comma: g(",", "<"),
  Period: g(".", ">"),
  Slash: g("/", "?"),
};

const RU: KeyGlyphMap = {
  Backquote: g("ё", "Ё"),
  Digit1: g("1", "!"),
  Digit2: g("2", '"'),
  Digit3: g("3", "№"),
  Digit4: g("4", ";"),
  Digit5: g("5", "%"),
  Digit6: g("6", ":"),
  Digit7: g("7", "?"),
  Digit8: g("8", "*"),
  Digit9: g("9", "("),
  Digit0: g("0", ")"),
  Minus: g("-", "_"),
  Equal: g("=", "+"),
  KeyQ: g("й", "Й"),
  KeyW: g("ц", "Ц"),
  KeyE: g("у", "У"),
  KeyR: g("к", "К"),
  KeyT: g("е", "Е"),
  KeyY: g("н", "Н"),
  KeyU: g("г", "Г"),
  KeyI: g("ш", "Ш"),
  KeyO: g("щ", "Щ"),
  KeyP: g("з", "З"),
  BracketLeft: g("х", "Х"),
  BracketRight: g("ъ", "Ъ"),
  Backslash: g("\\", "/"),
  KeyA: g("ф", "Ф"),
  KeyS: g("ы", "Ы"),
  KeyD: g("в", "В"),
  KeyF: g("а", "А"),
  KeyG: g("п", "П"),
  KeyH: g("р", "Р"),
  KeyJ: g("о", "О"),
  KeyK: g("л", "Л"),
  KeyL: g("д", "Д"),
  Semicolon: g("ж", "Ж"),
  Quote: g("э", "Э"),
  KeyZ: g("я", "Я"),
  KeyX: g("ч", "Ч"),
  KeyC: g("с", "С"),
  KeyV: g("м", "М"),
  KeyB: g("и", "И"),
  KeyN: g("т", "Т"),
  KeyM: g("ь", "Ь"),
  Comma: g("б", "Б"),
  Period: g("ю", "Ю"),
  Slash: g(".", ","),
};

export const LAYOUTS: Record<Layout, KeyGlyphMap> = { en: EN, ru: RU };

export const LAYOUT_LABELS: Record<Layout, string> = {
  en: "EN",
  ru: "RU",
};
